# Backpropagation: It is an algo for supervised learning of ANN ,given an ANN and error function it calculates the gradient of error function with respect to its loss
    gradient reffer to the derivation of the loss function with respect to thier weigths or biasis

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=["cgpa","profile_score","LPA"])
df  # data set created 

cgpa  profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model=Sequential() # to create architecture
model.add(Dense(2,activation="linear",input_dim=2))# adding first layer
model.add(Dense(1,activation="linear")) # adding second layer
model.summary() # to see are architecture

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
model.get_weights() # keras initialize with random weights and biasis

[array([[-0.6184245, -1.1607895],
        [ 1.0857238,  0.3754053]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0517253],
        [-0.9165685]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
optimizers=keras.optimizers.legacy.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizers)

In [12]:
df.iloc[:,0:-1].values

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]])

In [13]:
model.fit(df.iloc[:,0:-1].values,df["LPA"].values,epochs=75,verbose=1,batch_size=1) # in every epoch calculation will be made for every row 
# so in one epoch there are 4/4 which mean every row is calculated in each of the epoch
# we used .values because keras accept values in array format rather than datframe

Epoch 1/75
4/4 [==============================] - 0s 724us/step - loss: 24.2128
Epoch 2/75
4/4 [==============================] - 0s 712us/step - loss: 22.5489
Epoch 3/75
4/4 [==============================] - 0s 594us/step - loss: 20.9521
Epoch 4/75
4/4 [==============================] - 0s 637us/step - loss: 19.4257
Epoch 5/75
4/4 [==============================] - 0s 683us/step - loss: 17.9814
Epoch 6/75
4/4 [==============================] - 0s 525us/step - loss: 16.6298
Epoch 7/75
4/4 [==============================] - 0s 558us/step - loss: 15.3053
Epoch 8/75
4/4 [==============================] - 0s 623us/step - loss: 14.1558
Epoch 9/75
4/4 [==============================] - 0s 538us/step - loss: 12.9955
Epoch 10/75
4/4 [==============================] - 0s 564us/step - loss: 11.9957
Epoch 11/75
4/4 [==============================] - 0s 624us/step - loss: 11.0098
Epoch 12/75
4/4 [==============================] - 0s 495us/step - loss: 10.1392
Epoch 13/75
4/4 [====================

In [15]:
model.get_weights() # these are the otimal value of weights which we got using keras were are loss is at minimal

[array([[-0.74420863, -1.0353068 ],
        [ 0.9665745 ,  0.494361  ]], dtype=float32),
 array([-0.12395521,  0.12370627], dtype=float32),
 array([[ 0.9552806 ],
        [-0.80749464]], dtype=float32),
 array([-0.12759478], dtype=float32)]

In [16]:
# we did backpropagation for classification problem above , backpropagation takes place in every epoch for all the number of rows behind the scene

# for classification problem 

In [17]:
# creating a classification data
data={
    "CPA":[8,7,6,5],
    "Profile_score":[8,9,10,5],
    "Placement":[1,1,0,0]
}
df=pd.DataFrame(data)
df

CPA  Profile_score  Placement
0    8              8          1
1    7              9          1
2    6             10          0
3    5              5          0

In [18]:
model1=Sequential()
model1.add(Dense(2,activation="sigmoid",input_dim=2))# adding first layer
model1.add(Dense(1,activation="sigmoid")) # adding second layer
model1.summary() # to see are architecture

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model1.get_weights()

[array([[ 0.03803265, -0.56172645],
        [ 0.3731904 , -0.8081049 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.45265305],
        [1.0102154 ]], dtype=float32),
 array([0.], dtype=float32)]

In [22]:
optimizer1=keras.optimizers.legacy.Adam(learning_rate=0.001)
model1.compile(loss="binary_crossentropy",optimizer=optimizer1)

In [23]:
model1.fit(df.iloc[:,:-1].values,df["Placement"].values,epochs=50,verbose=1,batch_size=1)


Epoch 1/50
4/4 [==============================] - 0s 651us/step - loss: 0.7130
Epoch 2/50
4/4 [==============================] - 0s 685us/step - loss: 0.7118
Epoch 3/50
4/4 [==============================] - 0s 614us/step - loss: 0.7116
Epoch 4/50
4/4 [==============================] - 0s 641us/step - loss: 0.7117
Epoch 5/50
4/4 [==============================] - 0s 619us/step - loss: 0.7111
Epoch 6/50
4/4 [==============================] - 0s 632us/step - loss: 0.7111
Epoch 7/50
4/4 [==============================] - 0s 781us/step - loss: 0.7107
Epoch 8/50
4/4 [==============================] - 0s 596us/step - loss: 0.7108
Epoch 9/50
4/4 [==============================] - 0s 572us/step - loss: 0.7103
Epoch 10/50
4/4 [==============================] - 0s 603us/step - loss: 0.7100
Epoch 11/50
4/4 [==============================] - 0s 605us/step - loss: 0.7100
Epoch 12/50
4/4 [==============================] - 0s 634us/step - loss: 0.7096
Epoch 13/50
4/4 [==============================] 

In [24]:
# this was the method to train any nueral network in deep learning
# somehow in above case our loss was not reducing much reason could be anything but the main idea was to show how we work with neural networks